// Automatically generated by SVN_Revision_Extractor.exe at  3/ 2/2006 16:30:51. No need to modify this file really.
#define WOWD_SVN_REVISION 1379
#define WOWD_SVN_DATE "2007-03-03"
#define WOWD_SVN_TIME "10:11:19"
// END //